# -*- coding: utf-8 -*-
"""lab2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EgYy3MtTTT5h23LrEvu9nTRifjGGsQS1
"""



"""# 1.**List**

# 2. **Tuples**

# 3. **Sets**

# 4. **Dictionaries**

# 5. **Numpy**

# 6. **MatPlotLib**
"""

#list of 10 integrels


a=[7,8,3,4,5,6,9,10,1,2]

#sum,max,min
print('list',a)
print('sum:',sum(a))
print('max:',max(a))
print('min:',min(a))

#add and remove

a.append(11)
a.remove(9)

print('a after adding and removig element',a)

#sort the list in ascending and descending order

print('ascending oreder:',sorted(a))
print('decending order:',sorted(a,reverse=True))

#create a tuple with 5 strings

fruits=('apple','mango','banana','pineapple','watermelon')
print(fruits)
print('first element',fruits[1])
print('last element',fruits[3])

#try modify and grt error

#fruits.append('grapes')

#convert tuple into list

fruits_list=list(fruits)
fruits_list[2]='orange'
print('modified list',fruits_list)

#create two sets with common and unique elements

a={1,2,3,4,5}
b={4,5,6,7,8}

#perform union,intersection and differnence operations

print('union', a | b)
print('intersection',a & b)
print('difference',a-b)

#create dictionary

students={'ali':1,'malik':2,'umer':3,'qamar':4}

#print keys and values

print('keys',students.keys())
print('values', students.values())

#values updated

students['ali']=7
print('updated dictionary:',students)